### PR TITLE
Include script for a manuscript under preparation

### PR DESCRIPTION
**Pull request by yalinli2**
As suggested in the title, this commit adds a folder "_Li_et_al_2020" which includes the script and example results for a manuscript under preparation, cornstover biorefinery is used. The "_feedstock_composition_for_simulation.xlsx" file is needed for simulation.

PS, I'm doing this to partly to learn how to commit and push changes, I'd like to keep these private until the manuscript is submitted, let me know if I should postpone doing this, thanks!

### CODE REVIEW

**Comment by yoelcortes** [comment]
Congratulations on your first pull request. I can merge it in with one click, but you mentioned that you'd like to keep this private... In actuality, this is a public github repository so everything you commit is public (no way make anything private). Let me know if I should proceed to make this public or reject the request.

**Comment by yalinli2** [comment]
Ah I see, I think it's fine to make it public, but not include it in PyPI since it's still subject to change depending on what reviewers think. 

A side note is that the script runs on biosteam/biorefineries v2.4.1, so I'm not sure whether it's compatible with later versions. You can reject the pull request if you want modules in biorefineries to be always up to date, thanks!!!

**Comment by yoelcortes** [comment]
Cool, in your next update you can add a note that it relies on v2.4.1

**Comment by yalinli2** [comment]
Sounds great, will do!!!

**Pull request merged**
