### PR TITLE
Minor fixes and questions for the oilcane biorefinery

### PR DESCRIPTION
**Pull request by yalinli2**
Hi @yoelcortes , some minor fixes/questions I have on the oilcane biorefinery:

For the changes I made in this PR
1. `set_GWPCF(s.cellulase, 'cellulase', dilution=0.05)`:
```python
>>> from biorefineries import oilcane as oc
>>> oc.load('S2')
>>> oc.cellulase.show('cwt')

Stream: cellulase to <EnzymeHydrolysateMixer: M401>
 phase: 'l', T: 298.15 K, P: 101325 Pa
 composition (%): Water      95
                  Cellulase  5
                  ---------  6.62e+03 kg/hr
```
2. removal `set_GWPCF(s.catalyst, 'NaOH', 0.5)`: I believe this is just one extra line
3. `GWP_characterization_factors['methanol catalyst mixture'] = (
    GWP_characterization_factors['methanol'] * 0.75 + GWP_characterization_factors['NaOCH3'] * 0.25
)`
```python
>>> oc.load('O2')
>>> oc.catalyst.show('cwt')
Stream: catalyst to <StorageTank: T1105>
 phase: 'l', T: 298.15 K, P: 101325 Pa
 composition (%): Methanol  75
                  NaOCH3    25
                  --------  1 kg/hr
```

Additionally, there are some questions:
1. The [`GWP_displacement`](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/fdeeca2a81900ecf9ab8757268f4cdd9604804d5/biorefineries/oilcane/__init__.py#L1004) function is confusing to me - it looks like economic allocation
2. For fossil-based chemicals like `denaturant`, is the CO2 emission from its eventual breakdown considered?
3. The displacement GWP is very negative for the `O1` configuration:
```python
>>> oc.load('O1')
>>> df = oc.model.metrics_at_baseline()
>>> df[('Displacement allocation', 'Ethanol GWP [kg*CO2*eq / L]')]
-3.7965138579542024
```
And I think it decreased a significantly from the old results I got before the changes you made (not sure if it's in #39, but I used to have ~-4kg CO2/**gal**), do you know why this might have happened...?

Thank you!

### CODE REVIEW

**Comment by yoelcortes** [comment]
@yalinli2, thanks for the updates! Regarding your questions:

1. Sorry about the confusion. I think I accidentally named that function to GWP_displacement somehow and never used it. Best if that function is deleted. 
2. None of the biorefineries consume natural gas. Instead a fraction of the bagasse is diverted to completely satisfy all heat and power requirements. I like to account for fossil-fuel CO2 emissions by adding the eventual emissions to the characterization factor of the input. I believe the current value in `_lca_characterization_factors.py` is missing non-biogenic CO2 emissions (should be 0.33 + 2.74).
https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/fdeeca2a81900ecf9ab8757268f4cdd9604804d5/biorefineries/oilcane/_lca_characterization_factors.py#L37
3. Yes, this is because it is assuming ethanol is the main product, biodiesel displaces diesel, and electricity displaces the grid mix.

I believe the units were supposed to be per liter and I fixed it in recent commits.

**Comment by yalinli2** [comment]
Hi @yoelcortes , some followups:
1. Yep I think your metric function for the displacement GWP is correct, I removed that function in 8c5276b09203db3dcd7cfa4c0c184c27f374a78c
2. I also use that approach, but I'm not so sure here since you have a [`direct_nonbiogenic_emissions`](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/7afc05dc1f1f93dd360bdca7d0a82187eb24e4ef/biorefineries/oilcane/__init__.py#L942) function, but it's only accounting for natural gas streams, so I was asking is for other fossil streams like denaturant, methanol, the catalyst (methanol and NaHCO3), etc.
3. I understand this displacement approach, but I thought it's always been accounted for this way, so I was wondering what could cause a sudden decrease. About your comment on the unit, did you mean that there was a bug in unit labeling/calculation but now it was fixed, so the result changed?

Thank you!

**Comment by yoelcortes** [comment]
@yalinli2, thanks for following up! 

2. I forgot I had the [`direct_nonbiogenic_emissions`](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/7afc05dc1f1f93dd360bdca7d0a82187eb24e4ef/biorefineries/oilcane/__init__.py#L942) function. The system boundary for the LCA is cradle-to-biorefinery-gate, so non-biogenic emissions from burning the biofuels are not included. 
3. Previous units (per **gal**) was incorrect, it was updated to per **L**. Actual results for O1 (ignoring the incorrect units) haven't changed too much for more than a couple of months... The only small change was the addition of a bagasse drier and an increase in boiler efficiency.

Let me know if you have any further questions!
Thanks,

**Comment by yalinli2** [comment]
ohhh I see what you meant, all sounds good to me now, thanks!

**Pull request merged**
